name: CD Pipeline

on:
  push:
    branches:
      - devops

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

    
        
      - name: Build Docker Image
        run: |
          docker build --tag languagelearningfe:dev --file Dockerfile .
          

      - name: Save Docker Image
        run: |
          docker save languagelearningfe:dev > languagelearningfe.tar
          gzip languagelearningfe.tar

      - name: Transfer Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "languagelearningfe.tar.gz"
          target: /tmp/php

      - name: Load and Deploy Docker Image on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /tmp/php
            cd /tmp/php
            gunzip languagelearningfe.tar.gz
            rm -f languagelearningfe.tar.gz
            docker load < languagelearningfe.tar
            rm -f languagelearningfe.tar
            # cd /var/www/html/delve_fe/dev
            # git pull origin devops
            # docker-compose -f docker-compose.docker-compose.staging.yml down
            # docker-compose -f docker-compose.docker-compose.staging.yml up -d
