name: CD Pipeline

on:
  push:
    branches:
      - devops

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

    
        
      - name: Build Docker Image
        run: |
          docker build --tag delve-fe:staging --file Dockerfile .
          

      - name: Save Docker Image
        run: |
          docker save delve-fe:staging > delve-fe.tar
          gzip delve-fe.tar

      - name: Transfer Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "delve-fe.tar.gz"
          target: /tmp/php

      - name: Load and Deploy Docker Image on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /tmp/php
            cd /tmp/php
            rm -f delve-fe.tar.gz
            docker load < delve-fe.tar
            rm -f delve-fe.tar
            cd /var/www/html/delve_fe/dev
            git pull origin devops
            docker-compose -f docker-compose.docker-compose.staging.yml down
            docker-compose -f docker-compose.docker-compose.staging.yml up -d
