name: DEV CICD

on:
  push:
    branches:
      - devops

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
      
    - name: Update repo and build
      run: |
       cd /home/bulldozer/language_learning_fe
       git pull
       pnpm install
       rm -rf .next
       pnpm build
       cd /home/bulldozer
       tar -czvf next.tar.gz language_learning_fe/.next

       
    - name: Transfer Build Artifacts to Server
      run: |
        scp -i "${{ secrets.SSH_KEY }}" /home/bulldozer/next.tar.gz "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/delve_fe"
    

          
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "About to Deploy"
            cd /var/www/html/delve_fe/dev
            git reset --hard origin/dev
            git pull
            tar -xzvf ../next.tar.gz -C .
            rm ../next.tar.gz
            pm2 restart staging.delve.fun
