name: DEV CICD

on:
  push:
    branches:
      - devops

jobs:
  test-and-deploy:
    runs-on: self-hosted

    steps:
      
    - name: Update repo and build
      run: |
       cd /home/bulldozer/language_learning_fe
       git pull
       pnpm install
       rm -rf .next
       pnpm build
       cd /home/bulldozer/
       tar -czvf next.tar.gz language_learning_fe/.next

       
    - name: Transfer Build Artifacts to Server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" scp /home/bulldozer/next.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/delve_fe
        rm /home/bulldozer/next.tar.gz
        
        
    

          
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "About to Deploy"
            cd /var/www/html/delve_fe/
            tar -xzvf next.tar.gz -C .
            rm next.tar.gz
            mv language_learning_fe/.next dev
            rm language_learning_fe
            cd /var/www/html/delve_fe/dev
            git reset --hard origin/dev
            git pull
            pm2 restart staging.delve.fun
