name: DEV CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: [self-hosted,langlearn_fe_runners_3]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

    
        
      - name: Build Docker Image
        run: |
          docker build --tag delve-fe:dev --file Dockerfile .
          
      - name: Save Docker Image
        run: |
          docker save delve-fe:dev > delve-fe-dev.tar
          
      - name: Transfer Docker Image to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "delve-fe-dev.tar"
          target: /tmp/php

      - name: Load and Deploy Docker Image on Server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /tmp/php
            cd /tmp/php
            docker load < delve-fe-dev.tar
            rm -f delve-fe-dev.tar
            cd /var/www/html/delve_fe/dev
            git pull origin dev
            docker-compose -f docker-compose.yml down
            docker-compose --project-name delve-fe-dev -f docker-compose.yml up -d
